#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.6.7 (standalone edition) on Sat Jun 22 08:54:05 2013
#

import wx
import funcionesSimu as f
import PrincipalAdmin as P
# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Principal(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Principal.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.principal = wx.MenuItem(wxglade_tmp_menu, wx.ID_ANY, _("Principal"), _("Principal"), wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.principal)
        self.frame_1_menubar.Append(wxglade_tmp_menu, _("Archivo"))
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.label_1 = wx.StaticText(self, wx.ID_ANY, _(u"Ingrese el Angulo de Inclinación(º):"))
        self.txtAngulo = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_1_copy = wx.StaticText(self, wx.ID_ANY, _("Ingrese Velocidad Inicial(mtrs/seg):"))
        self.txtvel = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_1_copy_copy = wx.StaticText(self, wx.ID_ANY, _(u"Ingrese la Aceleración de Grav:"))
        self.txtGrav = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_1 = wx.Button(self, wx.ID_ANY, _("Simular"))

        self.__set_properties()
        self.txtvel.SetValidator(ContieneDatos())#activa la validacion
        self.txtGrav.SetValidator(ContieneDatos())#activa la validacion
        self.txtAngulo.SetValidator(ContieneDatos())#activa la validacion
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.OnPrincipal, self.principal)
        self.Bind(wx.EVT_TEXT, self.OnLetras, self.txtAngulo)
        self.Bind(wx.EVT_TEXT, self.OnLetras, self.txtvel)
        self.Bind(wx.EVT_TEXT, self.OnLetras, self.txtGrav)
        self.Bind(wx.EVT_BUTTON, self.OnSimulador, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Principal.__set_properties
        self.SetTitle(_("Tiro Parabolico"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Principal.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(5, 3, 0, 0)
        grid_sizer_1.Add(self.label_1, 0, 0, 0)
        grid_sizer_1.Add(self.txtAngulo, 0, wx.EXPAND, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.label_1_copy, 0, 0, 0)
        grid_sizer_1.Add(self.txtvel, 0, wx.EXPAND, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.label_1_copy_copy, 0, 0, 0)
        grid_sizer_1.Add(self.txtGrav, 0, wx.EXPAND, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.button_1, 0, wx.EXPAND, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnSimulador(self, event):  # wxGlade: Principal.<event_handler>
        frm=self
        if self.Validate():
            ang=int(frm.txtAngulo.GetValue())
            vel=int(frm.txtvel.GetValue())
        
            if vel>0:
                if vel <=500:
                    if ang>0:
                        if ang <91:
                            if vel < 20:
                                f.parabola1(self)
                            else:
                                f.parabola(self)
                        else:
                            dlg=wx.MessageDialog(self,'El angulo no puede ser mayor a 90', 'Atencion', wx.OK)
                            dlg.ShowModal()
                            dlg.Destroy()
                        
                    else:
                        dlg=wx.MessageDialog(self,'El angulo no puede ser Negativo', 'Atencion', wx.OK)
                        dlg.ShowModal()
                        dlg.Destroy()
                else:
                    dlg=wx.MessageDialog(self,'Solo Valores mayores a 0 y Menores a 999', 'Atencion', wx.OK)
                    dlg.ShowModal()
                    dlg.Destroy()
            else:
                dlg=wx.MessageDialog(self,'Solo Valores mayores a 0 y Menores a 999', 'Atencion', wx.OK)
                dlg.ShowModal()
                dlg.Destroy()
    def OnLetras(self, event):  # wxGlade: Principal.<event_handler>
        frm=self
        vel=frm.txtvel.GetValue()
        ang=frm.txtAngulo.GetValue()
        gra=frm.txtGrav.GetValue()
        if len(vel)> 3 or len(gra)>3 :
            dlg=wx.MessageDialog(self,'No puede tener mas de 3 caracteres numericos', 'Atencion', wx.OK)
            dlg.ShowModal()
            dlg.Destroy()
        
        else:
            if len(ang)>2:
                dlg=wx.MessageDialog(self,'El angulo no puede ser mayor a 90', 'Atencion', wx.OK)
                dlg.ShowModal()
                dlg.Destroy()
            else:
                if vel.isdigit()or ang.isdigit() or gra.isdigit():
                    pass
                else:
                    dlg=wx.MessageDialog(self,'No puede Tener Letras', 'Atencion', wx.OK)
                    dlg.ShowModal()
                    dlg.Destroy()
       
            
    def OnPrincipal(self, event):  # wxGlade: Principal.<event_handler>
        
        Ventana=P.Principal(self)
        Ventana.Show()
        self.Hide()
         

    
# end of class Principal
class ContieneDatos(wx.PyValidator):
    def __init__(self):
        wx.PyValidator.__init__(self)

    def Clone(self):
        """
        Note que todo validador debe implementar
        # el método Clone().
        """
        return ContieneDatos()

    def Validate(self, win):
        textCtrl = self.GetWindow()
        text = textCtrl.GetValue()
        if len(text) == 0:
            wx.MessageBox("Este campo debe contener algún texto!",
                          "Error")
            textCtrl.SetBackgroundColour("red")
            textCtrl.SetFocus()
            textCtrl.Refresh()
            return False
        else:
            textCtrl.SetBackgroundColour(
                               wx.SystemSettings_GetColour(
                               wx.SYS_COLOUR_WINDOW))
            textCtrl.Refresh()
            return True

    def TransferToWindow(self):
        return True

    def TransferFromWindow(self):
        return True
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.App()
    #wx.InitAllImageHandlers()
    frame_1 = Principal(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
